import { contextBridge, ipcRenderer } from 'electron'

export interface CaptionTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export interface SubtitleItem {
  start: number
  dur: number
  text: string
}

export interface FetchCaptionsResult {
  success: boolean
  captions: CaptionTrack[]
  error?: string
}

export interface FetchSubtitlesResult {
  success: boolean
  subtitles: SubtitleItem[]
  error?: string
}

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  fetchYoutubeCaptions: (videoId: string): Promise<FetchCaptionsResult> => 
    ipcRenderer.invoke('fetch-youtube-captions', videoId),
  fetchYoutubeSubtitles: (videoId: string, lang: string): Promise<FetchSubtitlesResult> =>
    ipcRenderer.invoke('fetch-youtube-subtitles', videoId, lang),
  // Electron store methods for redux-persist
  storeGet: (key: string): Promise<string | null> =>
    ipcRenderer.invoke('electron-store-get', key),
  storeSet: (key: string, value: string): Promise<boolean> =>
    ipcRenderer.invoke('electron-store-set', key, value),
  storeRemove: (key: string): Promise<boolean> =>
    ipcRenderer.invoke('electron-store-remove', key),
  // AI Chat methods
  getAIProviders: () =>
    ipcRenderer.invoke('get-ai-providers'),
  setAIProvider: (providerId: string) =>
    ipcRenderer.invoke('set-ai-provider', providerId),
  fetchAIModels: (providerId: string) =>
    ipcRenderer.invoke('fetch-ai-models', providerId),
  setAIModel: (providerId: string, modelId: string) =>
    ipcRenderer.invoke('set-ai-model', providerId, modelId),
  chatWithAIStream: (history: Array<{role: string, content: string}>, message: string, systemPrompt?: string) =>
    ipcRenderer.invoke('chat-with-ai-stream', history, message, systemPrompt),
  onAIChatChunk: (callback: (chunk: string) => void) => {
    ipcRenderer.on('ai-chat-chunk', (_event, chunk) => callback(chunk))
  },
  removeAIChatChunkListener: () => {
    ipcRenderer.removeAllListeners('ai-chat-chunk')
  },
  // API Key management methods
  getApiKeyStatus: () =>
    ipcRenderer.invoke('get-api-key-status'),
  getApiKeys: () =>
    ipcRenderer.invoke('get-api-keys'),
  setApiKey: (provider: 'gemini' | 'groq', key: string) =>
    ipcRenderer.invoke('set-api-key', provider, key),
  removeApiKey: (provider: 'gemini' | 'groq') =>
    ipcRenderer.invoke('remove-api-key', provider),
  testApiKey: (provider: 'gemini' | 'groq') =>
    ipcRenderer.invoke('test-api-key', provider),
  validateApiKey: (provider: 'gemini' | 'groq', key: string) =>
    ipcRenderer.invoke('validate-api-key', provider, key),
})
