import { contextBridge, ipcRenderer } from 'electron'

export interface CaptionTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export interface SubtitleItem {
  start: number
  dur: number
  text: string
}

export interface FetchCaptionsResult {
  success: boolean
  captions: CaptionTrack[]
  error?: string
}

export interface FetchSubtitlesResult {
  success: boolean
  subtitles: SubtitleItem[]
  error?: string
}

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  fetchYoutubeCaptions: (videoId: string): Promise<FetchCaptionsResult> => 
    ipcRenderer.invoke('fetch-youtube-captions', videoId),
  fetchYoutubeSubtitles: (videoId: string, lang: string): Promise<FetchSubtitlesResult> =>
    ipcRenderer.invoke('fetch-youtube-subtitles', videoId, lang),
})
