interface CaptionTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

interface SubtitleItem {
  start: number
  dur: number
  text: string
}

interface FetchCaptionsResult {
  success: boolean
  captions: CaptionTrack[]
  error?: string
}

interface FetchSubtitlesResult {
  success: boolean
  subtitles: SubtitleItem[]
  error?: string
}

interface Window {
  electronAPI: {
    platform: string
    fetchYoutubeCaptions: (videoId: string) => Promise<FetchCaptionsResult>
    fetchYoutubeSubtitles: (videoId: string, lang: string) => Promise<FetchSubtitlesResult>
  }
}
