interface CaptionTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

interface SubtitleItem {
  start: number
  dur: number
  text: string
}

interface FetchCaptionsResult {
  success: boolean
  captions: CaptionTrack[]
  error?: string
}

interface FetchSubtitlesResult {
  success: boolean
  subtitles: SubtitleItem[]
  error?: string
}

interface Window {
  electronAPI: {
    platform: string
    fetchYoutubeCaptions: (videoId: string) => Promise<FetchCaptionsResult>
    fetchYoutubeSubtitles: (videoId: string, lang: string) => Promise<FetchSubtitlesResult>
    // Electron store methods for redux-persist
    storeGet: (key: string) => Promise<string | null>
    storeSet: (key: string, value: string) => Promise<boolean>
    storeRemove: (key: string) => Promise<boolean>
  }
}
